#!/bin/bash
# Quick setup guide for fixing the current issues

echo "=================================================="
echo "🚀 RAG System Fix & Setup Guide"
echo "=================================================="

echo "📋 CURRENT ISSUES DETECTED:"
echo "1. Container marked as 'unhealthy'"
echo "2. Streamlit not accessible externally"
echo "3. YAML formatting errors in docker-compose.dev.yml"

echo ""
echo "🔧 FIXES APPLIED:"
echo "✅ Fixed YAML syntax in docker-compose.dev.yml"
echo "✅ Improved health check script"
echo "✅ Added debug mode with enhanced logging"
echo "✅ Fixed Streamlit external access configuration"
echo "✅ Added FastAPI port exposure"

echo ""
echo "🚀 DEPLOYMENT STEPS:"
echo ""
echo "1. STOP CURRENT CONTAINERS:"
echo "   sudo docker-compose -f docker-compose.dev.yml down"
echo ""
echo "2. REBUILD AND START IN DEBUG MODE:"
echo "   sudo docker-compose -f docker-compose.debug.yml up --build"
echo ""
echo "3. MONITOR THE STARTUP LOGS:"
echo "   The debug mode will show detailed startup information"
echo "   Look for error messages or configuration issues"
echo ""
echo "4. TEST CONNECTIVITY:"
echo "   Run: ./diagnose-connectivity.sh"
echo ""
echo "5. IF ISSUES PERSIST, TRY REGULAR MODE:"
echo "   sudo docker-compose -f docker-compose.dev.yml up -d"

echo ""
echo "🔍 DEBUGGING TOOLS AVAILABLE:"
echo "📊 ./troubleshoot-enhanced.sh    - Comprehensive diagnostics"
echo "🌐 ./diagnose-connectivity.sh   - Network connectivity analysis"
echo "🐛 docker-compose.debug.yml     - Debug mode with verbose logging"
echo "🔧 ./start-debug.sh             - Enhanced startup script"

echo ""
echo "🌐 EXTERNAL ACCESS:"
echo "Once running, access via your server's external IP:"
echo "- Streamlit UI: http://YOUR_SERVER_IP:8501"
echo "- FastAPI: http://YOUR_SERVER_IP:8000"
echo ""
echo "Make sure to:"
echo "✅ Allow ports 8501 and 8000 in firewall: sudo ufw allow 8501 && sudo ufw allow 8000"
echo "✅ Configure cloud security groups (if using GCP/AWS/Azure)"

echo ""
echo "🔑 ENVIRONMENT SETUP:"
echo "Ensure your .env file contains:"
echo "COHERE_API_KEY=your_cohere_api_key"
echo "GEMINI_API_KEY=your_gemini_api_key"

echo ""
echo "🎯 START HERE:"
echo "sudo docker-compose -f docker-compose.debug.yml up --build"
echo ""
echo "This will give you detailed logs to see exactly what's happening!"
